[package]
name = "my_project"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.17", features = ["derive"] }
caesar_cipher_cli = "0.1.2"

[lib]
name = "caesar_cipher_cli"
path = "src/lib.rs"
